In [2]:
print("hello airguard aqi")

hello airguard aqi


In [3]:
import pandas as pd

url = "https://huggingface.co/datasets/sachin-iitd/DelhiPollDataset/resolve/main/test.csv"

df = pd.read_csv(url)

df.head()


,dateTime,lat,long,pressure,temperature,humidity,pm1_0,pm2_5,pm10
0,2021-01-07 19:00:00+05:30,28.498,77.2938,988.75,32.20,35.64,85.86,137.98,150.68
1,2021-01-21 15:00:00+05:30,28.624,77.2734,988.44,36.08,18.14,49.19,78.99,86.57
2,2021-01-21 13:00:00+05:30,28.633,77.2734,987.85,35.67,18.47,56.52,91.86,96.19
3,2020-11-03 23:00:00+05:30,28.588,77.2224,988.95,30.82,33.63,73.57,103.09,109.04
4,2020-11-16 15:00:00+05:30,28.507,77.2938,993.66,33.76,38.16,47.95,76.54,83.87


In [ ]:
df.shape

(18537, 9)

In [ ]:
df.columns

Index(['dateTime', 'lat', 'long', 'pressure', 'temperature', 'humidity',
       'pm1_0', 'pm2_5', 'pm10'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18537 entries, 0 to 18536
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   dateTime     18537 non-null  object 
 1   lat          18537 non-null  float64
 2   long         18537 non-null  float64
 3   pressure     18537 non-null  float64
 4   temperature  18537 non-null  float64
 5   humidity     18537 non-null  float64
 6   pm1_0        18537 non-null  float64
 7   pm2_5        18537 non-null  float64
 8   pm10         18537 non-null  float64
dtypes: float64(8), object(1)
memory usage: 1.3+ MB


In [ ]:
df.describe()

,lat,long,pressure,temperature,humidity,pm1_0,pm2_5,pm10
count,18537.000000,18537.000000,18537.000000,18537.000000,18537.000000,18537.000000,18537.000000,18537.000000
mean,28.585283,77.243678,991.779830,29.604056,31.596641,114.752572,197.028641,214.834505
std,0.046647,0.045405,75.471759,5.214449,9.324703,52.050666,101.759131,110.431064
min,28.363000,77.100000,966.520000,13.490000,8.830000,21.040000,30.560000,31.890000
25%,28.552000,77.222400,989.400000,26.250000,24.420000,74.570000,121.650000,133.000000
50%,28.579000,77.253000,991.200000,29.900000,31.200000,106.630000,177.070000,192.600000
75%,28.624000,77.283600,993.030000,33.150000,38.280000,145.500000,248.250000,270.670000
max,28.741000,77.477400,11251.180000,123.270000,59.920000,329.200000,1113.500000,1388.500000


In [ ]:
df[df["temperature"] > 50]

,dateTime,lat,long,pressure,temperature,humidity,pm1_0,pm2_5,pm10
2076,2020-12-02 11:00:00+05:30,28.561,77.2428,1060.40,75.51,26.93,118.67,202.28,213.33
2867,2020-12-02 11:00:00+05:30,28.606,77.2734,1126.38,115.90,27.47,127.14,225.64,232.14
7280,2020-12-02 12:00:00+05:30,28.633,77.2734,1066.28,73.78,35.39,107.00,188.11,198.78
7441,2020-12-02 11:00:00+05:30,28.624,77.2632,1081.86,88.45,28.27,128.11,217.89,229.67
13382,2020-12-02 11:00:00+05:30,28.651,77.3040,1126.38,115.90,27.47,131.44,231.31,239.69
14215,2020-12-02 17:00:00+05:30,28.642,77.3142,1132.22,123.27,28.67,83.73,139.73,145.00
15190,2020-12-02 11:00:00+05:30,28.597,77.2632,1126.38,115.90,27.47,121.92,213.92,222.15
15546,2020-12-02 17:00:00+05:30,28.615,77.2836,1132.22,123.27,28.67,109.83,183.83,190.67


In [ ]:
(df["temperature"] > 50).sum()

np.int64(8)

In [5]:
df[df["pm2_5"] > 500].sum()

,0
dateTime,2020-12-07 12:00:00+05:302020-11-09 19:00:00+0...
lat,6233.534
long,16838.1348
pressure,215946.7
temperature,5646.84
humidity,8214.1
pm1_0,58110.2
pm2_5,122508.04
pm10,134238.9


In [3]:
import pandas as pd
train_url = "https://huggingface.co/datasets/sachin-iitd/DelhiPollDataset/resolve/main/train.csv"

train_df = pd.read_csv(train_url)

train_df.head()

,dateTime,lat,long,pressure,temperature,humidity,pm1_0,pm2_5,pm10
0,2021-01-20 09:00:00+05:30,28.633,77.2326,990.75,26.07,40.32,90.14,148.28,168.75
1,2021-01-16 08:00:00+05:30,28.651,77.2224,990.12,23.20,44.11,164.16,360.01,399.39
2,2021-01-02 18:00:00+05:30,28.561,77.2938,989.48,32.15,27.63,150.46,243.46,282.69
3,2020-11-19 13:00:00+05:30,28.552,77.1612,986.98,36.02,19.13,49.25,78.88,83.50
4,2021-01-11 15:00:00+05:30,28.561,77.1918,990.39,34.38,23.03,48.74,75.33,85.56


In [5]:
train_df["dateTime"] = pd.to_datetime(train_df["dateTime"])

In [7]:
train_df = train_df.sort_values("dateTime")

In [9]:
train_df[["dateTime", "pm2_5"]].head(10)

,dateTime,pm2_5
28478,2020-11-01 00:00:00+05:30,486.15
51035,2020-11-01 00:00:00+05:30,395.48
59086,2020-11-01 01:00:00+05:30,437.59
68844,2020-11-01 01:00:00+05:30,461.67
63954,2020-11-01 02:00:00+05:30,501.74
59094,2020-11-01 02:00:00+05:30,478.18
25745,2020-11-01 03:00:00+05:30,522.03
262,2020-11-01 03:00:00+05:30,494.58
7975,2020-11-01 03:00:00+05:30,549.04
1334,2020-11-01 04:00:00+05:30,546.42


In [11]:
train_df = train_df.reset_index(drop=True)

In [13]:
train_df[["lat", "long"]].drop_duplicates().shape

(285, 2)

In [15]:
train_df[["lat", "long"]].drop_duplicates().head(10)

,lat,long
0,28.579,77.2326
1,28.579,77.2224
7,28.570,77.2224
12,28.498,77.2938
13,28.525,77.2836
14,28.516,77.2836
15,28.489,77.2938
16,28.543,77.2734
17,28.570,77.2530
18,28.561,77.2632


In [17]:
duplicates = train_df.duplicated(
      subset=["lat", "long", "dateTime"],
          keep=False
)
duplicates.sum()

np.int64(0)

In [19]:
train_df["future_pm2_5"] = (
      train_df.groupby(["lat", "long"])["pm2_5"].shift(-1)
      )


In [21]:
train_df[["lat", "long", "dateTime", "pm2_5", "future_pm2_5"]].head(10)

,lat,long,dateTime,pm2_5,future_pm2_5
0,28.579,77.2326,2020-11-01 00:00:00+05:30,486.15,461.67
1,28.579,77.2224,2020-11-01 00:00:00+05:30,395.48,437.59
2,28.579,77.2224,2020-11-01 01:00:00+05:30,437.59,501.74
3,28.579,77.2326,2020-11-01 01:00:00+05:30,461.67,478.18
4,28.579,77.2224,2020-11-01 02:00:00+05:30,501.74,522.03
5,28.579,77.2326,2020-11-01 02:00:00+05:30,478.18,549.04
6,28.579,77.2224,2020-11-01 03:00:00+05:30,522.03,507.67
7,28.570,77.2224,2020-11-01 03:00:00+05:30,494.58,507.00
8,28.579,77.2326,2020-11-01 03:00:00+05:30,549.04,546.42
9,28.579,77.2326,2020-11-01 04:00:00+05:30,546.42,496.96


In [23]:
train_df["future_pm2_5"].isna().sum()

np.int64(285)

In [25]:
train_df = train_df.dropna(subset=["future_pm2_5"])

In [27]:
train_df.shape

(73863, 10)

In [29]:
X = train_df.drop(columns=["future_pm2_5"])
y = train_df["future_pm2_5"]

In [32]:
X.head()

,dateTime,lat,long,pressure,temperature,humidity,pm1_0,pm2_5,pm10
0,2020-11-01 00:00:00+05:30,28.579,77.2326,989.01,25.04,32.53,239.24,486.15,538.22
1,2020-11-01 00:00:00+05:30,28.579,77.2224,988.99,30.47,28.80,222.18,395.48,420.59
2,2020-11-01 01:00:00+05:30,28.579,77.2224,989.19,29.13,29.10,235.07,437.59,472.06
3,2020-11-01 01:00:00+05:30,28.579,77.2326,988.70,30.08,25.07,237.91,461.67,491.43
4,2020-11-01 02:00:00+05:30,28.579,77.2224,988.81,30.14,29.10,253.60,501.74,548.41


In [35]:
y.head()

,future_pm2_5
0,461.67
1,437.59
2,501.74
3,478.18
4,522.03


In [36]:
X.shape

(73863, 9)

In [38]:
y.shape

(73863,)

In [39]:
train_df["hour"] = train_df["dateTime"].dt.hour

In [41]:
train_df["day_of_week"] = train_df["dateTime"].dt.dayofweek

In [43]:
train_df[["dateTime", "hour", "day_of_week"]].head(10)

,dateTime,hour,day_of_week
0,2020-11-01 00:00:00+05:30,0,6
1,2020-11-01 00:00:00+05:30,0,6
2,2020-11-01 01:00:00+05:30,1,6
3,2020-11-01 01:00:00+05:30,1,6
4,2020-11-01 02:00:00+05:30,2,6
5,2020-11-01 02:00:00+05:30,2,6
6,2020-11-01 03:00:00+05:30,3,6
7,2020-11-01 03:00:00+05:30,3,6
8,2020-11-01 03:00:00+05:30,3,6
9,2020-11-01 04:00:00+05:30,4,6


In [48]:
train_df["month"] = train_df["dateTime"].dt.month

In [47]:
train_df[["dateTime", "hour", "day_of_week", "month"]].head(10)

,dateTime,hour,day_of_week,month
0,2020-11-01 00:00:00+05:30,0,6,11
1,2020-11-01 00:00:00+05:30,0,6,11
2,2020-11-01 01:00:00+05:30,1,6,11
3,2020-11-01 01:00:00+05:30,1,6,11
4,2020-11-01 02:00:00+05:30,2,6,11
5,2020-11-01 02:00:00+05:30,2,6,11
6,2020-11-01 03:00:00+05:30,3,6,11
7,2020-11-01 03:00:00+05:30,3,6,11
8,2020-11-01 03:00:00+05:30,3,6,11
9,2020-11-01 04:00:00+05:30,4,6,11


In [53]:
X = train_df.drop(columns=["future_pm2_5", "dateTime"])
y = train_df["future_pm2_5"]

In [55]:
split = int(len(train_df) * 0.8)

X_train = X.iloc[:split]
X_val = X.iloc[split:]

y_train = y.iloc[:split]
y_val = y.iloc[split:]

In [57]:
X_train.shape, X_val.shape, y_train.shape, y_val.shape

((59090, 11), (14773, 11), (59090,), (14773,))

In [59]:
from sklearn.ensemble import RandomForestRegressor

In [66]:
model = RandomForestRegressor(
      n_estimators=100,
          random_state=42,
              n_jobs=-1
)

In [67]:
model.fit(X_train, y_train)

RandomForestRegressor(n_jobs=-1, random_state=42)

In [69]:
predictions = model.predict(X_val)

In [71]:
predictions[:10]

array([307.9278, 422.8967, 346.1461, 416.0871, 360.9873, 380.8214,
       322.2577, 376.6021, 449.1113, 351.788 ])

In [73]:
y_val.head(10).values

array([292.7 , 477.12, 359.3 , 593.94, 266.3 , 419.84, 258.55, 333.33,
       613.35, 262.78])

In [75]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_val, predictions)

print("MAE:", mae)

MAE: 44.2079100250457


In [77]:
from sklearn.metrics import mean_squared_error
import numpy as np

rmse = np.sqrt(mean_squared_error(y_val, predictions))

print("RMSE:", rmse)

RMSE: 61.9361855526869


In [79]:
from sklearn.metrics import r2_score

r2 = r2_score(y_val, predictions)

print("R²:", r2)

R²: 0.5003558663312402


In [81]:
train_df["pm2_5_lag1"] = (
      train_df.groupby(["lat", "long"])["pm2_5"].shift(1)
)

In [83]:
train_df[[
      "lat",
          "long",
              "dateTime",
                  "pm2_5",
                      "pm2_5_lag1"
                      ]].head(10)


,lat,long,dateTime,pm2_5,pm2_5_lag1
0,28.579,77.2326,2020-11-01 00:00:00+05:30,486.15,NaN
1,28.579,77.2224,2020-11-01 00:00:00+05:30,395.48,NaN
2,28.579,77.2224,2020-11-01 01:00:00+05:30,437.59,395.48
3,28.579,77.2326,2020-11-01 01:00:00+05:30,461.67,486.15
4,28.579,77.2224,2020-11-01 02:00:00+05:30,501.74,437.59
5,28.579,77.2326,2020-11-01 02:00:00+05:30,478.18,461.67
6,28.579,77.2224,2020-11-01 03:00:00+05:30,522.03,501.74
7,28.570,77.2224,2020-11-01 03:00:00+05:30,494.58,NaN
8,28.579,77.2326,2020-11-01 03:00:00+05:30,549.04,478.18
9,28.579,77.2326,2020-11-01 04:00:00+05:30,546.42,549.04


In [86]:
train_df["pm2_5_lag2"] = (
      train_df.groupby(["lat", "long"])["pm2_5"].shift(2)
      )

train_df["pm2_5_lag3"] = (
      train_df.groupby(["lat", "long"])["pm2_5"].shift(3)
      )


In [88]:
train_df[[
      "dateTime",
          "pm2_5",
              "pm2_5_lag1",
                  "pm2_5_lag2",
                      "pm2_5_lag3"
                      ]].head(10)


,dateTime,pm2_5,pm2_5_lag1,pm2_5_lag2,pm2_5_lag3
0,2020-11-01 00:00:00+05:30,486.15,NaN,NaN,NaN
1,2020-11-01 00:00:00+05:30,395.48,NaN,NaN,NaN
2,2020-11-01 01:00:00+05:30,437.59,395.48,NaN,NaN
3,2020-11-01 01:00:00+05:30,461.67,486.15,NaN,NaN
4,2020-11-01 02:00:00+05:30,501.74,437.59,395.48,NaN
5,2020-11-01 02:00:00+05:30,478.18,461.67,486.15,NaN
6,2020-11-01 03:00:00+05:30,522.03,501.74,437.59,395.48
7,2020-11-01 03:00:00+05:30,494.58,NaN,NaN,NaN
8,2020-11-01 03:00:00+05:30,549.04,478.18,461.67,486.15
9,2020-11-01 04:00:00+05:30,546.42,549.04,478.18,461.67


In [90]:
train_df = train_df.dropna(
      subset=["pm2_5_lag1", "pm2_5_lag2", "pm2_5_lag3"]
      )


In [92]:
train_df.shape

(73238, 16)

In [95]:
features = [
      "lat",
          "long",
              "pressure",
                  "temperature",
                      "humidity",
                          "pm1_0",
                              "pm2_5",
                                  "pm10",
                                      "hour",
                                          "day_of_week",
                                              "month",
                                                  "pm2_5_lag1",
                                                      "pm2_5_lag2",
                                                          "pm2_5_lag3"
                                                          ]

X = train_df[features]
y = train_df["future_pm2_5"]


In [97]:
split = int(len(train_df) * 0.8)

X_train = X.iloc[:split]
X_val = X.iloc[split:]

y_train = y.iloc[:split]
y_val = y.iloc[split:]

In [99]:
X_train.shape, X_val.shape, y_train.shape, y_val.shape

((58590, 14), (14648, 14), (58590,), (14648,))

In [102]:
model2 = RandomForestRegressor(
      n_estimators=100,
          random_state=42,
              n_jobs=-1
              )

model2.fit(X_train, y_train)


RandomForestRegressor(n_jobs=-1, random_state=42)

In [104]:
predictions2 = model2.predict(X_val)

In [106]:
predictions2[:10]

array([346.8958, 462.8354, 443.5532, 508.9989, 349.7784, 355.681 ,
       347.0178, 485.0537, 374.0397, 528.0292])

In [108]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae2 = mean_absolute_error(y_val, predictions2)
rmse2 = np.sqrt(mean_squared_error(y_val, predictions2))
r2_2 = r2_score(y_val, predictions2)

print("MAE:", mae2)
print("RMSE:", rmse2)
print("R²:", r2_2)

MAE: 43.40450845849262
RMSE: 60.815427513559854
R²: 0.49990211416374164


In [109]:
import joblib

joblib.dump(model2, "airguard_random_forest.pkl")

['airguard_random_forest.pkl']

In [1]:
from google.colab import files

files.download("airguard_random_forest.pkl")

FileNotFoundError: Cannot find file: airguard_random_forest.pkl

In [2]:
print(X_train.columns.tolist())

NameError: name 'X_train' is not defined